/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as WorkerRouteRouteImport } from './routes/worker/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkerIndexRouteImport } from './routes/worker/index'
import { Route as WorkerLogUsageRouteImport } from './routes/worker/log-usage'
import { Route as WorkerLogRepairRouteImport } from './routes/worker/log-repair'
import { Route as WorkerLogProductionRouteImport } from './routes/worker/log-production'
import { Route as WorkerLogDowntimeRouteImport } from './routes/worker/log-downtime'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedStaticCostsRouteImport } from './routes/_authenticated/static-costs'
import { Route as AuthenticatedPurchaseOrdersRouteImport } from './routes/_authenticated/purchase-orders'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedMinesRouteImport } from './routes/_authenticated/mines'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedEquipmentRouteImport } from './routes/_authenticated/equipment'
import { Route as AuthenticatedDowntimeRouteImport } from './routes/_authenticated/downtime'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerRouteRoute = WorkerRouteRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerIndexRoute = WorkerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkerRouteRoute,
} as any)
const WorkerLogUsageRoute = WorkerLogUsageRouteImport.update({
  id: '/log-usage',
  path: '/log-usage',
  getParentRoute: () => WorkerRouteRoute,
} as any)
const WorkerLogRepairRoute = WorkerLogRepairRouteImport.update({
  id: '/log-repair',
  path: '/log-repair',
  getParentRoute: () => WorkerRouteRoute,
} as any)
const WorkerLogProductionRoute = WorkerLogProductionRouteImport.update({
  id: '/log-production',
  path: '/log-production',
  getParentRoute: () => WorkerRouteRoute,
} as any)
const WorkerLogDowntimeRoute = WorkerLogDowntimeRouteImport.update({
  id: '/log-downtime',
  path: '/log-downtime',
  getParentRoute: () => WorkerRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaticCostsRoute =
  AuthenticatedStaticCostsRouteImport.update({
    id: '/static-costs',
    path: '/static-costs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersRoute =
  AuthenticatedPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinesRoute = AuthenticatedMinesRouteImport.update({
  id: '/mines',
  path: '/mines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipmentRoute = AuthenticatedEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDowntimeRoute = AuthenticatedDowntimeRouteImport.update({
  id: '/downtime',
  path: '/downtime',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/worker': typeof WorkerRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/downtime': typeof AuthenticatedDowntimeRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/mines': typeof AuthenticatedMinesRoute
  '/production': typeof AuthenticatedProductionRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/static-costs': typeof AuthenticatedStaticCostsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/api/chat': typeof ApiChatRoute
  '/worker/log-downtime': typeof WorkerLogDowntimeRoute
  '/worker/log-production': typeof WorkerLogProductionRoute
  '/worker/log-repair': typeof WorkerLogRepairRoute
  '/worker/log-usage': typeof WorkerLogUsageRoute
  '/worker/': typeof WorkerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/downtime': typeof AuthenticatedDowntimeRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/mines': typeof AuthenticatedMinesRoute
  '/production': typeof AuthenticatedProductionRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/static-costs': typeof AuthenticatedStaticCostsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/api/chat': typeof ApiChatRoute
  '/worker/log-downtime': typeof WorkerLogDowntimeRoute
  '/worker/log-production': typeof WorkerLogProductionRoute
  '/worker/log-repair': typeof WorkerLogRepairRoute
  '/worker/log-usage': typeof WorkerLogUsageRoute
  '/worker': typeof WorkerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/worker': typeof WorkerRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/downtime': typeof AuthenticatedDowntimeRoute
  '/_authenticated/equipment': typeof AuthenticatedEquipmentRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/mines': typeof AuthenticatedMinesRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/_authenticated/static-costs': typeof AuthenticatedStaticCostsRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/api/chat': typeof ApiChatRoute
  '/worker/log-downtime': typeof WorkerLogDowntimeRoute
  '/worker/log-production': typeof WorkerLogProductionRoute
  '/worker/log-repair': typeof WorkerLogRepairRoute
  '/worker/log-usage': typeof WorkerLogUsageRoute
  '/worker/': typeof WorkerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/worker'
    | '/auth'
    | '/analytics'
    | '/clients'
    | '/dashboard'
    | '/downtime'
    | '/equipment'
    | '/inventory'
    | '/maintenance'
    | '/mines'
    | '/production'
    | '/purchase-orders'
    | '/static-costs'
    | '/suppliers'
    | '/api/chat'
    | '/worker/log-downtime'
    | '/worker/log-production'
    | '/worker/log-repair'
    | '/worker/log-usage'
    | '/worker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/clients'
    | '/dashboard'
    | '/downtime'
    | '/equipment'
    | '/inventory'
    | '/maintenance'
    | '/mines'
    | '/production'
    | '/purchase-orders'
    | '/static-costs'
    | '/suppliers'
    | '/api/chat'
    | '/worker/log-downtime'
    | '/worker/log-production'
    | '/worker/log-repair'
    | '/worker/log-usage'
    | '/worker'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/worker'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/downtime'
    | '/_authenticated/equipment'
    | '/_authenticated/inventory'
    | '/_authenticated/maintenance'
    | '/_authenticated/mines'
    | '/_authenticated/production'
    | '/_authenticated/purchase-orders'
    | '/_authenticated/static-costs'
    | '/_authenticated/suppliers'
    | '/api/chat'
    | '/worker/log-downtime'
    | '/worker/log-production'
    | '/worker/log-repair'
    | '/worker/log-usage'
    | '/worker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  WorkerRouteRoute: typeof WorkerRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/': {
      id: '/worker/'
      path: '/'
      fullPath: '/worker/'
      preLoaderRoute: typeof WorkerIndexRouteImport
      parentRoute: typeof WorkerRouteRoute
    }
    '/worker/log-usage': {
      id: '/worker/log-usage'
      path: '/log-usage'
      fullPath: '/worker/log-usage'
      preLoaderRoute: typeof WorkerLogUsageRouteImport
      parentRoute: typeof WorkerRouteRoute
    }
    '/worker/log-repair': {
      id: '/worker/log-repair'
      path: '/log-repair'
      fullPath: '/worker/log-repair'
      preLoaderRoute: typeof WorkerLogRepairRouteImport
      parentRoute: typeof WorkerRouteRoute
    }
    '/worker/log-production': {
      id: '/worker/log-production'
      path: '/log-production'
      fullPath: '/worker/log-production'
      preLoaderRoute: typeof WorkerLogProductionRouteImport
      parentRoute: typeof WorkerRouteRoute
    }
    '/worker/log-downtime': {
      id: '/worker/log-downtime'
      path: '/log-downtime'
      fullPath: '/worker/log-downtime'
      preLoaderRoute: typeof WorkerLogDowntimeRouteImport
      parentRoute: typeof WorkerRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/static-costs': {
      id: '/_authenticated/static-costs'
      path: '/static-costs'
      fullPath: '/static-costs'
      preLoaderRoute: typeof AuthenticatedStaticCostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders': {
      id: '/_authenticated/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mines': {
      id: '/_authenticated/mines'
      path: '/mines'
      fullPath: '/mines'
      preLoaderRoute: typeof AuthenticatedMinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment': {
      id: '/_authenticated/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthenticatedEquipmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/downtime': {
      id: '/_authenticated/downtime'
      path: '/downtime'
      fullPath: '/downtime'
      preLoaderRoute: typeof AuthenticatedDowntimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDowntimeRoute: typeof AuthenticatedDowntimeRoute
  AuthenticatedEquipmentRoute: typeof AuthenticatedEquipmentRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedMinesRoute: typeof AuthenticatedMinesRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedPurchaseOrdersRoute: typeof AuthenticatedPurchaseOrdersRoute
  AuthenticatedStaticCostsRoute: typeof AuthenticatedStaticCostsRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDowntimeRoute: AuthenticatedDowntimeRoute,
  AuthenticatedEquipmentRoute: AuthenticatedEquipmentRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedMinesRoute: AuthenticatedMinesRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedPurchaseOrdersRoute: AuthenticatedPurchaseOrdersRoute,
  AuthenticatedStaticCostsRoute: AuthenticatedStaticCostsRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface WorkerRouteRouteChildren {
  WorkerLogDowntimeRoute: typeof WorkerLogDowntimeRoute
  WorkerLogProductionRoute: typeof WorkerLogProductionRoute
  WorkerLogRepairRoute: typeof WorkerLogRepairRoute
  WorkerLogUsageRoute: typeof WorkerLogUsageRoute
  WorkerIndexRoute: typeof WorkerIndexRoute
}

const WorkerRouteRouteChildren: WorkerRouteRouteChildren = {
  WorkerLogDowntimeRoute: WorkerLogDowntimeRoute,
  WorkerLogProductionRoute: WorkerLogProductionRoute,
  WorkerLogRepairRoute: WorkerLogRepairRoute,
  WorkerLogUsageRoute: WorkerLogUsageRoute,
  WorkerIndexRoute: WorkerIndexRoute,
}

const WorkerRouteRouteWithChildren = WorkerRouteRoute._addFileChildren(
  WorkerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  WorkerRouteRoute: WorkerRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
